notifications:
  email: false
language:
- cpp
os:
- linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libopenal-dev
    - libjpeg-dev
    - libudev-dev
    - libxrandr-dev
    - libfreetype6-dev
    - libvorbis-dev
    - libflac-dev
    - gcc-7
    - g++-7
install:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then export CXX="g++-7"; fi
- git clone https://github.com/SFML/SFML.git
- cd SFML
- mkdir install
- mkdir build
- cd build
- cmake -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_INSTALL_FRAMEWORK_PREFIX=../install
  -DSFML_BUILD_FRAMEWORKS=FALSE -DBUILD_SHARED_LIBS=TRUE ..
- make
- make install
- cd ../../
script:
- mkdir build/
- cd build/
- cmake -DSFML_DIR=/home/travis/build/tuanphuc/FlappyBirdLab/SFML/install/lib/cmake/SFML ..
- make
- make install
before_deploy:
  - zip FlappyBirdLab-$TRAVIS_OS_NAME ./bin/FlappyBirdLab/ -r
  - ls # To check the zip file is created correctly
deploy:
  release: FlappyBirdLab
  description: 'FlappyBirdLab master branch release'
  skip_cleanup: true
  provider: releases
  file: FlappyBirdLab-$TRAVIS_OS_NAME.zip
  on:
    tags: true